# Site settings
title: Sheheryar Zaidi
tag_text: Sheheryar Zaidi
description: Sheheryar Zaidi

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

plugins:
  - jemoji